import Head from 'next/head'
import Navbar from './components/Navbar';
import Hero from './components/Hero';
import Minting from './components/Minting';
import Roadmap from './components/Roadmap';
import Team from './components/Team';
import FAQ from './components/FAQ';
import Footer from './components/Footer';

export default function Home() {
  return (
    <>
      <Head>
				<title>Scary Eyes</title>
				<meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/pro.ico" />
			</Head>
      <Navbar  />
      <Hero />
      <Minting />
      <Roadmap />
      <Team />
      <FAQ />
      <Footer />
    </>
  )
}
